version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/services/express

permissions:
  - object: /home/ubuntu/services/express
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
  - object: /home/ubuntu/services/express
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_npm_packages.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu