import express from 'express';
import { orderController } from './order.controller';
import commentsRoutes from '../comments/comment.routes';
import { hasRolePermission } from '../../middlewares';
import { validateParamId } from '../../middlewares/validate';
import { upload } from '../../upload/upload.routes';
import { workOrderValidator, updateWorkOrderValidator } from './workOrder.validator';
import { validate } from '../../middlewares/validator.middleware';
import { payloadCryptoMultipartMiddleware } from '../../middlewares/payloadCrypto.middleware';
import { idempotencyMiddleware } from '../../middlewares/idempotency.middleware';

export default (router: express.Router) => {
    const orderRouter = express.Router();
    orderRouter.use(idempotencyMiddleware);
    orderRouter.get('/', orderController.getAll);
    orderRouter.get('/get-work-order', orderController.getAllWorkOrders);
    orderRouter.get('/activity/:id', validateParamId, orderController.getActivity);
    orderRouter.get('/history/:id', validateParamId, orderController.getHistory);
    orderRouter.get('/:id', validateParamId, orderController.getOrderById);
    orderRouter.post('/', hasRolePermission('workOrder', 'create_work_order'), workOrderValidator, validate, orderController.createOrder);
    orderRouter.post('/status', orderController.getOrderStatus);
    orderRouter.post('/summary', orderController.getSummaryData);
    orderRouter.post('/overview-summary', orderController.getOverviewSummary);
    orderRouter.post('/created-vs-completed', orderController.getCreatedVsCompleted);
    orderRouter.post('/execution-summary', orderController.getExecutionSummary);
    orderRouter.post('/on-time-vs-overdue', orderController.getOnTimeVsOverdue);
    orderRouter.post('/time-to-complete', orderController.getTimeToComplete);
    orderRouter.post('/by-type', orderController.getByType);
    orderRouter.post('/source-mix', orderController.getSourceMix);
    orderRouter.post('/asset-maintenance', orderController.getAssetMaintenance);
    orderRouter.post('/request-funnel', orderController.getRequestFunnel);
    orderRouter.post('/parts-impact', orderController.getPartsImpact);
    orderRouter.post('/completed-with-inspection', orderController.getCompletedWithInspection);
    orderRouter.post('/completed-by-user', orderController.getCompletedByUser);
    orderRouter.post('/time-vs-cost', orderController.getTimeVsCost);
    orderRouter.post('/planner-readiness', orderController.getPlannerReadiness);
    orderRouter.post('/repeating-work-orders', orderController.getRepeatingWorkOrders);
    orderRouter.post('/pending', orderController.getPendingOrders);
    orderRouter.post('/priority', orderController.getOrderPriority);
    orderRouter.post('/monthly-count', orderController.getMonthlyCount);
    orderRouter.post('/planned-unplanned', orderController.getPlannedUnplanned);
    orderRouter.put('/status/:id', validateParamId, hasRolePermission('workOrder', 'update_work_order_status'), orderController.statusUpdateOrder);
    orderRouter.put('/:id', validateParamId, updateWorkOrderValidator, validate, orderController.updateOrder);
    orderRouter.patch('/:id', validateParamId, updateWorkOrderValidator, validate, orderController.updateOrderSubmitData);
    orderRouter.delete('/:id', validateParamId, hasRolePermission('workOrder', 'delete_work_order'), orderController.remove);
    orderRouter.post('/:id/attachments', validateParamId, (req, res, next) => { req.params.folderName = 'work_order'; next(); }, upload.array('files', 12), payloadCryptoMultipartMiddleware, orderController.uploadAttachments);
    const commentRouter = express.Router({ mergeParams: true });
    orderRouter.use("/:id/comments", commentsRoutes(commentRouter));
    router.use('/orders', orderRouter);
};
